---
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - checkout
      - run:
          name: install HashiCorp packer
          command: |
            export VER="1.5.4"
            wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
            unzip packer_${VER}_linux_amd64.zip
            sudo mv packer /usr/local/bin

      - run:
          name: install Code Deploy agent
          command: |
            sudo apt-get install ruby
            cd /home/ubuntu
            wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
            chmod +x ./install
            sudo ./install auto
            
      - run:
          name: Validate the packer config and run Packer build
          command: |
            packer validate -var 'source_ami='${source_ami} ubuntu-ami.json
            packer build \
            -var 'aws_access_key='${aws_access_key} \
            -var 'aws_secret_key='${aws_secret_key} \
            -var 'aws_region='${aws_region} \
            -var 'ami_users='${ami_users} \
            -var 'source_ami='${source_ami} \
            ubuntu-ami.json

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
            branches:
              only:
                - master     