---
version: 2
jobs:
  ami_img:
    steps:
      -run:
        name: install phoshiCorp packer
        command: |
          export VER="1.5.4"
          wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          unzip packer_${VER}_linux_amd64.zip
          sudo mv packer /usr/local/bin
          packer